Tareas/Core/EscuelaNegocios_MartinSanchez/EscuelaNegocios_MartinSanchez/Models/Club.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EscuelaNegocios_MartinSanchez.Models
{
    [Table("Clubs")]
    public class Club
    {
        [Key]
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Students { get; set; }
        public int DepartmentId { get; set; }
        public virtual Department? Department { get; set; }
    }
}

Tareas/Core/EscuelaNegocios_MartinSanchez/EscuelaNegocios_MartinSanchez/Controllers/ClubController.cs
using EscuelaNegocios_MartinSanchez.Data;
using EscuelaNegocios_MartinSanchez.Models;
using EscuelaNegocios_MartinSanchez.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EscuelaNegocios_MartinSanchez.Controllers
{
    [Authorize(Roles = "Admin, Student")]
    public class ClubController : Controller
    {
        private readonly ApplicationDbContext? _db;

        public ClubController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var clubs = await _db!.Clubs.Include(c => c.Department).ToListAsync();
            return View(clubs);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddClub() 
        {
            var departmentList = await _db!.Departments.Select(d => new
            {
                Id = d.Id,
                Value = d.Name
            }).ToListAsync();

            ClubAddClubViewModel vm = new ClubAddClubViewModel();
            vm.DepartmentList = new SelectList(departmentList, "Id", "Value");

            return View(vm);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddClub(Club club)
        {
            _db!.Clubs.Add(club);
            await _db.SaveChangesAsync();

            return RedirectToAction("Index");
        }


    }
}

Tareas/Core/EscuelaNegocios_MartinSanchez/EscuelaNegocios_MartinSanchez/Controllers/DepartmentController.cs
using EscuelaNegocios_MartinSanchez.Data;
using EscuelaNegocios_MartinSanchez.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EscuelaNegocios_MartinSanchez.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DepartmentController : Controller
    {
        private readonly ApplicationDbContext? _db;

        public DepartmentController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var departments = await _db!.Departments.ToListAsync();
            return View(departments);
        }

        public IActionResult AddDepartment()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddDepartment(Department department)
        {
            _db!.Add(department);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DepartmentDetails(int id)
        {
            Department? department = await _db!.Departments.SingleOrDefaultAsync(d => d.Id == id);

            return View(department);
        }

    }
}

Tareas/Core/EscuelaNegocios_MartinSanchez/EscuelaNegocios_MartinSanchez/Controllers/StudentClubController.cs
using EscuelaNegocios_MartinSanchez.Data;
using EscuelaNegocios_MartinSanchez.Models;
using EscuelaNegocios_MartinSanchez.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EscuelaNegocios_MartinSanchez.Controllers
{
    public class StudentClubController : Controller
    {
        private readonly ApplicationDbContext? _db;

        public StudentClubController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> ClubStudents(int id)
        {
            Club? club = await _db!.Clubs.SingleOrDefaultAsync(c => c.Id == id);
            ViewBag.ClubName = club!.Name;

            var clubStudents = await _db!.StudentsClubs
                .Where(sc => sc.ClubId == id)
                .Include(sc => sc.Student)
                .ToListAsync();

            return View(clubStudents);
        }

        public async Task<IActionResult> AddStudentClub(int clubId)
        {
            var studentsList = await _db!.Students.Select(s => new
            {
                Id = s.Id,
                Value = s.Name
            }).ToListAsync();

            StudentClubAddStudentClubViewModel vm = new StudentClubAddStudentClubViewModel();
            vm.StudentList = new SelectList(studentsList, "Id", "Value");

            Club? club = await _db!.Clubs.SingleOrDefaultAsync(c => c.Id == clubId);
            vm.StudentClub = new StudentClub
            {
                ClubId = clubId,
                Club = club
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> AddStudentClub(StudentClubAddStudentClubViewModel vm)
        {
            var studentClub = await _db!.StudentsClubs.Where(sc => sc.StudentId == vm.StudentClub!.StudentId && sc.ClubId == vm.StudentClub.ClubId).SingleOrDefaultAsync();
            Club? club = await _db.Clubs.SingleOrDefaultAsync(c => c.Id == vm.StudentClub!.ClubId);
            Student? student = await _db!.Students.SingleAsync(s => s.Id == vm.StudentClub!.StudentId);
            vm.StudentClub!.Club = club;
            vm.StudentClub!.Student = student;
            if (studentClub != null)
            {
                return View("StudentAlreadyInClub", vm);
            }
            else
            {

                _db.StudentsClubs.Add(vm.StudentClub!);
                club!.Students++;
                _db.Clubs.Update(club);

                await _db.SaveChangesAsync();
                return RedirectToAction("Index", "Club");
            }
        }
    }
}

Tareas/Core/EscuelaNegocios_MartinSanchez/EscuelaNegocios_MartinSanchez/Views/Club/AddClub.cshtml
@using EscuelaNegocios_MartinSanchez.ViewModels
@model ClubAddClubViewModel

<h1>Add Club</h1>
<div class="container">
    <div class="row mb-3">
        <div class="col-md-7 offset-3">
            <form asp-action="AddClub">
                <div class="form-group">
                    <label asp-for="Club!.Name"></label>
                    <input asp-for="Club!.Name" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Club!.Department!.Name"></label>
                    <select asp-for="Club!.DepartmentId" asp-items="@Model.DepartmentList" class="form-select" >
                        <option>-Choose a Department</option>
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-success">Save and Back to Clubs Index</button>
                </div>
            </form>
        </div>
    </div>
    <a asp-action="Index" class="btn btn-outline-dark">Back</a>
</div>

Tareas/Core/EscuelaNegocios_MartinSanchez/EscuelaNegocios_MartinSanchez/Views/Club/Index.cshtml
@using EscuelaNegocios_MartinSanchez.Models
@model List<Club>

<h1>Index</h1>

<a asp-action="AddClub" class="btn btn-primary">Add Club</a>
@if(Model.Count() == 0){
    <p>No Clubs in database yet</p>
}else{
    <table class="table table-bordered">
        <thead class="table-primary">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Number students</th>
                <th>Department</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var club in Model)
            {
                <tr>
                    <td>@club.Id</td>
                    <td>
                        <a 
                            asp-action="AddStudentClub"
                            asp-controller="StudentClub"
                            asp-route-clubId="@club.Id">
                            @club.Name
                        </a>
                    </td>
                    <td>
                        <a 
                            asp-action="ClubStudents"
                            asp-controller="StudentClub" 
                            asp-route-id="@club.Id"
                        >
                        @club.Students
                        </a>
                    </td>
                    <td>
                        <a 
                        asp-action="DepartmentDetails" 
                        asp-controller="Department" 
                        asp-route-id="@club.DepartmentId"
                        >
                        @club!.Department!.Name
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}