Tareas/AWS/PracticaS3Bucket/PracticaS3Bucket/Models/ErrorViewModel.cs
namespace PracticaS3Bucket.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tareas/AWS/PracticaS3Bucket/PracticaS3Bucket/Models/S3ObjectDto.cs
namespace PracticaS3Bucket.Models
{
    public class S3ObjectDto
    {
        public string? Name { get; set; }
        public string? PresignedUrl { get; set; }
    }
}

Tareas/AWS/PracticaS3Bucket/PracticaS3Bucket/Controllers/BucketsController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaS3Bucket.Services;

namespace PracticaS3Bucket.Controllers
{
    public class BucketsController : Controller
    {
        private readonly AwsS3Service _awsS3Service;

        public BucketsController(AwsS3Service awsS3Service)
        {
            _awsS3Service = awsS3Service;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _awsS3Service.GetAllBucketAsync();

            return View(response);
        }

        public IActionResult Create()
        {   
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string bucketName)
        {
            var response = await _awsS3Service.CreateBucketAsync(bucketName);

            string viewContent = $"Se ha creado el bucket {bucketName} con exito";

            if (!response)
            {
                viewContent = $"Se ha producido un error al crear el bucket {bucketName}";
            }

            return View("OperationStatus", viewContent);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string bucketName) 
        {
            var response = await _awsS3Service.DeleteBucketAsync(bucketName);

            string viewContent = $"El bucket {bucketName} se ha eliminado con exito!";

            if (!response)
            {
                viewContent = $"Se ha producido un error al eliminar el bucket {bucketName}";
            }

            return View("OperationStatus", viewContent);
        }
    }
}

Tareas/AWS/PracticaS3Bucket/PracticaS3Bucket/Controllers/FilesController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaS3Bucket.Models;
using PracticaS3Bucket.Services;

namespace PracticaS3Bucket.Controllers
{
    public class FilesController : Controller
    {
        private readonly AwsS3Service _awsS3Service;

        public FilesController(AwsS3Service awsS3Service)
        {
            _awsS3Service = awsS3Service;
        }

        public async Task<IActionResult> Index(string bucketName)
        {
            IEnumerable<S3ObjectDto> response = await _awsS3Service.GetAllFilesAsync(bucketName);
            ViewBag.bucketName = bucketName;

            return View(response);
        }

        public IActionResult Upload(string bucketName)
        {
            ViewBag.bucketName = bucketName;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file, string bucketName)
        {
            if (file == null || file.Length == 0)
            {
                return View("OperationStatus", "Advertencia el archivo no puede estar vacío.");
            }

            var response = await _awsS3Service.UploadFileAsync(file, bucketName);

            if (!response.Contains("successfully"))
            {
                response = $"Se ha producido un error al subir el archivo al bucket {bucketName}";
                return View("OperationStatus", response);
            }

            return RedirectToAction("Index", new { bucketName });
        }

        [HttpPost]
        public async Task<IActionResult> Download(string bucketName, string key)
        {
            var response = await _awsS3Service.GetFileByKeyAsync(bucketName, key);

            if (response == null)
            {
                return View("OperationStatus", "Se ha producido un error al descargar el archivo");
            }

            var contentType = "application/octet-stream";

            return File(response, contentType, key);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string bucketName, string key)
        {
            var response = await _awsS3Service.DeleteFileAsync(bucketName, key);

            if (!response)
            {
                return View("OperationStatus", "Se ha producido un error al eliminar el archivo");
            }

            return RedirectToAction("Index", new { bucketName});
        }
    }
}

Tareas/AWS/PracticaS3Bucket/PracticaS3Bucket/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PracticaS3Bucket.Models;

namespace PracticaS3Bucket.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tareas/AWS/PracticaS3Bucket/PracticaS3Bucket/Views/Shared/OperationStatus.cshtml
@model string 

@if(Model.Contains("exito")){
    <div class="card bg-success opacity-75" >
        <div class="card-body">
            <p>@Model</p>
        </div>
    </div>
}

@if(Model.Contains("error")){
    <div class="card bg-danger opacity-75" >
        <div class="card-body">
            <p>@Model</p>
        </div>
    </div>
}
@if(Model.Contains("Advertencia"))
{
    <div class="card bg-warning bg-opacity-50">
        <div class="card-body">
            <p>⚠️ @Model</p>
        </div>
    </div>
}

Tareas/AWS/PracticaS3Bucket/PracticaS3Bucket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaS3Bucket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaS3Bucket.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaS3Bucket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Buckets" asp-action="Index">Buckets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PracticaS3Bucket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>